### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by GildasLepennetier** [jumphone/BEER#2]
It is unclear in the vignette which data is used as input.

From the demo data, I can see that the input is a data frame ( https://github.com/jumphone/BEER/raw/master/DATA/demodata.zip )

Using a Seurat object, I can use the .simple_combine function to merge assays using the [["RNA"]] slot:

`DATA=.simple_combine(  Seurat_1 [["RNA"]],  Seurat_2 [["RNA"]] )`

The result is a sparse Matrix of class "dgCMatrix".

But impossible to use the FILL=T, I have the following error:

```
Error in rbind2(argl[[i]], r) : 
  no method for coercing this S4 class to a vector
Called from: rbind2(argl[[i]], r)
```

1) Do I use the .simple_combine function properly?
2) What can I do concerning the FILL=T option (I actually should have complete gene record)

**Comment by jumphone** [comment]
Thanks for using BEER.

1. DATA = .simple_combine( as.matrix(Seurat_1 [["RNA"]]), as.matrix(Seurat_2 [["RNA"]]) )$combine

2. If you want to have complete gene record, please set FILL to TRUE. 

Best,
Feng
