### ISSUE TITLE
 unused argument (reduction.use = "umap")

### ISSUE THREAD

**Issue by yueli8** [jumphone/BEER#3]
Hello,

Thank you for developing so nice software "BEER".

I followed the: https://github.com/jumphone/BEER

Thanks in advance for any great help!

Best,

Yue

`> DimPlot(pbmc_batch, reduction.use='umap', group.by='batch', pt.size=0.1) 
Error in DimPlot(pbmc_batch, reduction.use = "umap", group.by = "batch",  : 
  unused argument (reduction.use = "umap")`

**Comment by jumphone** [comment]
You can try “ DimPlot(pbmc, reduction = "umap")”.

**Comment by yueli8** [comment]
Hello jumphone,

Thank you so much for your great help!

Best!

Yue
